### ISSUE TITLE
Covariance Matrix

### ISSUE THREAD

**Issue by LorenzoBonanni** [michael-lim/VOOTreeSearch.jl#1]
How do you choose which value to give to the Covariance Matrix used for sampling Actions from the Multivariate Gaussian?

**Comment by michaelhlim** [comment]
Hi Lorenzo, thanks for your interest in our VPW work. It's been a while since I've done any work in this line of research so my memory is a bit hazy, but I will try to answer my best. 

I employ a two step procedure:
1. Pick an initial variance value/covariance matrix  -- I think I used isotropic covariance (sigma^2 * I) in my experiments unless I knew beforehand some action space requirements/domain knowledge (for instance, you know one action space dimension has a lot larger range than the other). I would still encourage you to at least use diagonal for simplicity, and for the second step below.
2. Optimize that as one of the hyperparameters -- I've utilized CEM in my experiments to do hyperparameter sweeps.

Typically, I've found that something in the order of 1/10-1/100 of the action space size/length usually seemed to do pretty well. You can see some of the hyperparameter optimization schemes in the vomcpow_opt.jl files.

Hope that helps!

**Comment by LorenzoBonanni** [comment]
Thanks a lot for your answer!
